Add View for mailbox, and controller
redjen/IST311 pull request #27
Opened 2017-08-12 19:53 UTC by maximdumont

2017-08-12 21:38 UTC, redjen requested changes
This does work but it's not quite the functionality that we'd designed. The mailbox should be a list of notifications that were sent to a patient. It should look similar to this:
https://docs.google.com/document/d/1sslQWoNQDEYTMLsUuEBKx70UpBtnMYKD2vC7pxpHVU0/edit#bookmark=id.caskave684pr

So we need to keep a list of status changes (or strings containing the message) somewhere and display them on this tab. Maybe we could do something like PatientCollection (MessageCollection or whatever) that has an observable list for displayed on this tab? The controller wouldn't need to change much, just use the new list.

What do you think?

2017-08-12 21:38 UTC, redjen commented on src/app/TabViewController.java
> +         tabPane.getTabs().addAll(homeTab, patientListTab, admittingTab,mailboxTab);
The mailbox tab is for patients, not staff.

2017-08-14 01:01 UTC, lmdgr34 approved these changes

2017-08-14 02:28 UTC, redjen approved these changes
I apparently have to approve this also before merge since I'd requested changes earlier. So here you go.

2017-08-14 02:29 UTC, merged